### ISSUE TITLE
HDMI port (use USB C to HDMI from Unitek instead)

### ISSUE THREAD

**Issue by skystar7** [dragons3232/Lenovo-gaming-3-10750h-hackintosh-EFI#4]
Thanks for your help

Did you able to connect your Hackintosh to an external monitor using the USB C to HDMI adapter?

**Comment by dragons3232** [comment]
Hi @skystar7, yes I am able to. You need to install driver for unitek adapter you have. You can find and download driver for your model at https://www.unitek-products.com/pages/drivers-adapters

**Comment by skystar7** [comment]
Many thanks :)

**Comment by dragons3232** [comment]
FYI, if there is still someone struggling to find a working HDMI adapter, here is what I am using unitek-y3702. Driver is at https://drive.google.com/drive/folders/10GVxpoXVKuERqKDGJQMEqbLeKIA8-6jO

![image](https://user-images.githubusercontent.com/49872282/151640599-c06bf548-6744-4878-b712-14fbc177d4b3.png)

**Comment by dragons3232** [comment]
DO NOT use this one for hackintosh lenovo gaming 3. It ONLY works for Macbook with thunder bolt USB C. You can use it for Macbook, Mac mini just fine. But it does NOT work on lenovo gaming 3 :| . Perhaps because USB C port on lenovo gaming 3 is not thunder bolt
![image](https://user-images.githubusercontent.com/49872282/151640952-29c581b2-1da7-44c4-a994-bfdbeb0f7d7f.png)
